81 stockpile fetch and deposit
martinjonsson01/OOPP-WITH-THE-BOIS pull request #108
Opened 2021-10-23 15:23 UTC by Matte02

## Summary
Will make Pawns get materials to build and to empty their inventories while harvesting to the stockpile.

## Test Coverage
![image](https://user-images.githubusercontent.com/55716109/138562244-e99023e1-0409-4553-a869-00d7009e5600.png)
![image](https://user-images.githubusercontent.com/55716109/138562259-ac01870d-63b8-4ca9-98e4-13ec78014ae1.png)
![image](https://user-images.githubusercontent.com/55716109/138562268-45ebe5ff-b3d3-4531-b24e-b20072a14617.png)
![image](https://user-images.githubusercontent.com/55716109/138562273-ec02a553-8ad9-4d4d-a457-453759d8b270.png)
![image](https://user-images.githubusercontent.com/55716109/138562280-ea69cea5-72b5-4c21-9b5b-cc9c08e8b943.png)
![image](https://user-images.githubusercontent.com/55716109/138562285-979685ac-9d01-4a8d-a806-0c68d96db135.png)
![image](https://user-images.githubusercontent.com/55716109/138562297-d369872b-bcf7-4aa5-9fcb-db7bb7e20c67.png)

## Definition of Done
- [x] Completed all Tasks of the User Story
- [x] The Tasks have tests and they all pass
- [x] Overall test coverage is >= 90%
- [x] A UML class diagram of the newly implemented User Story is done and included in the README.md of the package

## Diagrams
Done, will be added when all other diagrams are updated.

Closes #81

2021-10-23 15:31 UTC, JacobBredin commented on src/main/java/com/thebois/models/world/World.java
> +                                                                  .equals(StructureType.TOWN_HALL))
Why is this needed? Or what is it for?

2021-10-23 15:38 UTC, Matte02 commented on src/main/java/com/thebois/models/world/World.java
> +                                                                  .equals(StructureType.TOWN_HALL))
It's used to allow the method to return Town Hall when searching for stockpiles.

2021-10-23 15:43 UTC, JacobBredin commented on src/main/java/com/thebois/models/world/World.java
> +                                                                  .equals(StructureType.TOWN_HALL))
Okay, now I see. 👍

2021-10-23 16:18 UTC, jonathan-lindqvist requested changes
![bild](https://user-images.githubusercontent.com/47867973/138563899-019229da-6af8-4cfb-b963-3f013e7373aa.png)
Great work, just look over the comments, shouldn't be anything major! 😄

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/IPositionable.java
> + * Something that has a position.
You can add author now that you created this

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/actions/DoNextAction.java
> + * </p>
Author 🖊️

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/actions/DoNextAction.java
> + * performed.
We say it can always be preformed, but `canPreform` returns false?

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> + * Action give item from performer to a storable.
📖

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +    private static final float MINIMUM_GIVE_DISTANCE = 2f;
Seconds?
And 2 what?

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/actions/HarvestAction.java
> +            resource.getPosition().distanceTo(performer.getPosition()) <= 1.0f;
Question
Should we have a magic number here or is it not worth it?

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/actions/TakeItemAction.java
> + * Action take takes an item from a takeable.
✏️

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
>       * Instantiates with a way of finding resources.
We have structures and resources now

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
> +            structureFinder.getNearbyStructureOfType(position, StructureType.STOCKPILE);
dosent change anything, but it removes a unneccesssary variable, we can just do 
` structureFinder.getNearbyStructureOfType(performer.getPosition(), StructureType.STOCKPILE);`
we dont seem to use it anywhere else in this method

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +    private int buildingState = 0;
Feels a bit vague what these two mean, might be nice to have a comments explaining them 😄

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +        if (maybeStructure.isEmpty()) return ActionFactory.createDoNothing();
These are very similar across the a lot of methods, some parts seem pasted? Because once again we have position being used just once

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +        final IStructure stockpile = maybeStockpile.get();
Exact same snippet of code in my last comment, only change is maybestockpile

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/roles/FisherRole.java
> +     * @param structureFinder The locator of structures.
since we call it `structureFinder` maybe `finder` should be `resourceFinder`, the same in the other files we added this

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/roles/LumberjackRole.java
> +     * @param finder          The locator of resources.
resourceFinder

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/beings/roles/MinerRole.java
> +     * @param finder          The locator of resources.
resourceFinder

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/inventory/IInventory.java
> -    int numberOf(ItemType itemType);
🤩

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/world/resources/Water.java
> +    private static final float HARVEST_TIME = 0.3f;
isnt this super fast?

2021-10-23 16:18 UTC, jonathan-lindqvist commented on src/main/java/com/thebois/models/world/structures/Stockpile.java
> +class Stockpile extends AbstractStructure implements ITakeable, IStorable {
Shouldn't this just implement `IInventory ` since thats exactly all it does now?

2021-10-23 16:40 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/DoNextAction.java
> + * performed.
Oh, should be changed to is always completed, good catch

2021-10-23 16:41 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/HarvestAction.java
> +            resource.getPosition().distanceTo(performer.getPosition()) <= 1.0f;
Should probably be changed like the other actions, menaing have a constant called mininum harvest distance or something. 
Changing it

2021-10-23 16:49 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
> +            structureFinder.getNearbyStructureOfType(position, StructureType.STOCKPILE);
We are using it twice in the method and it makes the line less than 100 chars long, but can change it to `performer.getPosition()` if we want.

2021-10-23 16:55 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
> +            structureFinder.getNearbyStructureOfType(position, StructureType.STOCKPILE);
Nvm it was in the method above, will change it in this one, and all others that only uses it once.

2021-10-23 16:57 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +    private int buildingState = 0;
I tried giving them an explanation, I realize now I could use a boolean for the build state, needed an int before as I had 3 build state. Do we want to keep the int or change it to boolean?

2021-10-23 17:01 UTC, martinjonsson01 approved these changes
Phenomenal work, this was a real complex story but you got it to function while still testing everything! 

Left a bunch of suggestions, but I think it'd be okay even if we had to merge it as-is.

![image](https://user-images.githubusercontent.com/12572888/138565224-3b223890-38ed-47ad-b851-d733532502b9.png)

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/IPositionable.java
> + */
Missing author tag.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/IActionPerformer.java
> +public interface IActionPerformer extends Serializable, IStorable, ITakeable, IPositionable {
This, right here, is what we in the business call

***interface segregation***

👍 👍

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/ActionFactory.java
> +    }
Ahh, that's how you solved it!

Nice, that's exactly what I was thinking `DoNothingAction` should've done in the beginning, but then someway along the line turned into an do-idle-stuff action instead.

Neat.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/BuildAction.java
> +        return isCloseEnough && performerHasNeededItem;
Supremely readable, nice job!

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/DoNextAction.java
> + */
Missing author tag.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/DoNextAction.java
> + * Be careful when using this action as it may create an infinity loop. As this action can always be
typo

infinity -> infinite

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/DoNextAction.java
> + * performed.
Actually, the javadoc is out of date. The implementation makes it so that the action can never be performed, but the javadoc says it can always be performed.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/DoNextAction.java
> +    public boolean equals(final Object o) {
style

o -> other

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
question

It's a bit confusing that the action is `GiveItem` but in the constructor you never specify which item to give. So is it more like `GiveAnyItem`? Or how does it pick which item to give?

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/TakeItemAction.java
> + */
Missing author tag.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/TakeItemAction.java
> +        final ITakeable takeable, final ItemType itemType, final Position takeablePosition) {
I'm noticing that you're always passing `IStoreable` and `ITakeable` together with positions, is that always the case, or are there use-cases where you don't care about the position of the "storable"/"takable" and only want to access it? 

I'm imagining that you always want to know where you need to be to give/take something, so maybe these two interfaces should extends `IPositionable`, what do you think?

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
> +        if (!isEmptying) {
style

You should switch around the if-statement so you don't need the negation. It's easier to read `if(isEmptying)` than to interpret it as `if (not isEmptying)`.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
> +        }
This turned out really clean, nicely done!

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
> +    }
question

This looks like a copy/paste of `createMoveToResource`, were you not able to factor the common parts out into a single method? 

Ah, I suppose that's really difficult since they use different finders and different interfaces returned.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
> +        return ActionFactory.createGiveItem(storable, structure.getPosition());
style

Looks a bit weird to have the declaration of `storable` split from its assignment, just to have the return statement at the end of the method.

Could you move the return statement that uses the `storable` into the inside of the if-statement? Maybe java complains if you do that.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +        }
"buildingState" is quite vague, it's hard to understand what it really means for a builder to be in a specific "building state". Could you maybe use a private enum instead? Something like

```java
private enum BuilderState {
    FETCHING_RESOURCES = 0,
    BUILDING_STRUCTURE = 1
}
```

I think you should still be able to increment the enum with `buildingState++`, since enums really are 16-bit numbers with titles. 

It would make the code a lot more readable if it said `if (buildingState == BuilderState.FETCHING_RESOURCES)` rather than what it is right now.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +    }
Maybe I'm misremembering but don't you have the exact same method in `AbstractHarvesterRole`? If that is the case, then this should be broken out into a method in `ActionFactory` called `createMoveToStockpile` or something similar.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +    }
Same here, isn't this used in two places in the exact same way?

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +        }
style

Should be broken out into a method.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +        return ActionFactory.createTakeItem(takeable, nextNeededItem, stockpile.getPosition());
Here you can make it a lot more readable as well by moving the parts on line 133-139 into the inside of the if-clause on line 127.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/inventory/IStorable.java
> + */
Missing author tag.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/inventory/ITakeable.java
> + */
Missing author.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/inventory/ITakeable.java
> +    IItem takeNextItem();
style

I've seen you use this method quite a bit, but I always asked the question "what qualifies as the *next* item?", and here I finally see that it's the *first* item in the inventory.

Maybe the method should be called `takeFirstItem` or `takeTopItem`.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/world/ITile.java
> -    Position getPosition();
One more step closer to perfection!

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/world/World.java
> +                                                      && structure.getType()
style

This whole filter-conditional should be broken out into a method with a clear name like `isStorable(structure)`.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/world/structures/AbstractStructure.java
> +                allNeededItems.get(itemType) - deliveredItems.numberOf(itemType);
![image](https://user-images.githubusercontent.com/12572888/138564616-b187cb6a-fe86-4f22-808a-75d3dd4e3061.png)

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/world/structures/AbstractStructure.java
> +        if (!allNeededItems.containsKey(itemType)) return 0;
Is this just in `AbstractStructure` and not in `IBuildable`? If that is the case, then it should probably be added to `IBuildable` and an `@Override` tag should be here, if it already is, then it's missing an override tag.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/world/structures/IBuildable.java
> +     * Counts the amount of times still needed to build the structure.
style

Not really the amount of times, rather the amount of items.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/test/java/com/thebois/models/beings/BeingTests.java
> +    private static final IInventory inventory = mock(IInventory.class);
It's a bit iffy to have a static mock, because then it's the same for all the different tests. 

It's better to have it be re-instantiated in a setup-method with `@BeforeEach` so that a new inventory is used for each test.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/test/java/com/thebois/models/beings/BeingTests.java
> +    }
The best kind of tests 😩 

Hey, at least we can actually verify that it delegates, that's something!

2021-10-23 17:01 UTC, martinjonsson01 commented on src/test/java/com/thebois/models/beings/actions/GiveItemActionTests.java
> +        // Arrange
style

No need for empty clauses of the triple-A test structure.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/test/java/com/thebois/models/beings/actions/TakeItemActionTests.java
> +        verify(performer, times(1)).tryAdd(any());
Not gonna lie, I really like this exact way of structuring tests.

1) The clear AAA-structure.
2) The clutter of instantiation moved to a setup-method.
3) The use of clear variable names.
4) Mocks with very clear purpose.
5) Clear assertions in the form of verify-calls.

Great job.

2021-10-23 17:01 UTC, martinjonsson01 commented on src/test/java/com/thebois/models/beings/roles/BuilderRoleTests.java
> +    public void obtainNextActionReturnsIdleActionWhenOneRotationHaveGoneAndNoStockpileCouldBeFoundToFill() {
Really great test names, all around. I'm able to tell what you're testing in each method without having to actually read the method, and if I am intrigued by the name then I can read the test for an exact description of how its done. 

Well done. 
![image](https://user-images.githubusercontent.com/12572888/138565076-83360d79-b434-4000-b5d1-985be91f818e.png)

2021-10-23 17:01 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +        if (maybeStructure.isEmpty()) return ActionFactory.createDoNothing();
They are kind of copy pasted, I guess I could extract 
```
  final Optional<IStructure> maybeStructure =
            finder.getNearbyStructureOfType(position, StructureType.STOCKPILE);
        if (maybeStructure.isEmpty()) return ActionFactory.createDoNothing();
```

into a method and then check if the returned value is null keep going and if it is something else instantly return.  Didn't really like how that looked but maybe it is better than what we have now.

2021-10-23 17:03 UTC, Matte02 commented on src/main/java/com/thebois/models/world/structures/Stockpile.java
> +class Stockpile extends AbstractStructure implements ITakeable, IStorable {
Very true, changing it

2021-10-23 17:03 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/BuilderRole.java
> +    private int buildingState = 0;
Take a look at my suggestion for this below, before implementing it as a boolean.

2021-10-23 17:04 UTC, Matte02 commented on src/main/java/com/thebois/models/world/resources/Water.java
> +    private static final float HARVEST_TIME = 0.3f;
Not really if you take into consideration that the pawn can atm carry 200 fishes.

2021-10-23 17:05 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/world/resources/Water.java
> +    private static final float HARVEST_TIME = 0.3f;
We can probably save the balance-tweaking until tomorrow when we go through it all before turning it in.

2021-10-23 17:08 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/TakeItemAction.java
> +        final ITakeable takeable, final ItemType itemType, final Position takeablePosition) {
It was more the case of inventory doesn't have a position, so takeable and storable should probably not have a position. I guess I could make an interface that extends takeable and positionable but I don't know about that.

2021-10-23 17:09 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
> +    }
That was indeed the problem.

2021-10-23 17:10 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/TakeItemAction.java
> +        final ITakeable takeable, final ItemType itemType, final Position takeablePosition) {
Ah, that's true. It sounds a bit weird for an inventory to have a position...

Unless? 

Actually, is there a case where you want to access an inventory without knowing if you're near enough to be able to access it? Isn't it always the case that you also want to check the distance to the holder of the inventory?

2021-10-23 17:13 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/roles/AbstractHarvesterRole.java
> +    }
The thing is, whenever you encounter a bunch of methods doing the same thing in the exact same order and same structure, but using minorly different variables or types, that is a sign that there is an underlying abstraction waiting to be created. 

If we could identify the common idea between all of these methods, then that would be the missing abstraction. Would make the roles a whole lot cleaner. 

But this isn't the worst thing ever, so leave it as-is. I'll try to come up with a nice hotfix if I can figure out the underlying abstraction, but we might not be able to fix this before the deadline.

2021-10-23 17:15 UTC, Matte02 commented on src/main/java/com/thebois/models/world/structures/AbstractStructure.java
> +        if (!allNeededItems.containsKey(itemType)) return 0;
Yup, was just missing the `@Override` tag

2021-10-23 17:16 UTC, Matte02 commented on src/main/java/com/thebois/models/world/structures/IBuildable.java
> +     * Counts the amount of times still needed to build the structure.
Let's just say that items and times are almost spelled the same. And me being tired missed that I misspelled it.

2021-10-23 17:16 UTC, Matte02 commented on src/test/java/com/thebois/models/beings/BeingTests.java
> +    private static final IInventory inventory = mock(IInventory.class);
I'll take a look at this.

2021-10-23 17:20 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/TakeItemAction.java
> +        final ITakeable takeable, final ItemType itemType, final Position takeablePosition) {
Hmm
Actually, you are probably right, but I feel like it would be a pain the ass to make sure the position of the inventory is always the same as the pawn. I Will take a look at this when I've handled the rest of the review.

2021-10-23 17:28 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/TakeItemAction.java
> +        final ITakeable takeable, final ItemType itemType, final Position takeablePosition) {
Good call, this isn't necessary at all and should be very low priority.

Oh, yeah, the inventory still shouldn't have its own position. Since an inventory is always a part of some entity, the position it returns should be the position of the entity. 

But I see what you're saying, that still means that the inventory needs a reference to the entity, which is whack. Maybe `IPositionable` is what saves the day here, since the "holder" of the inventory (i.e. `Being` or `Structure`) always implements it, then the inventory can just take an `IPositionable` in its constructor, and whenever inventory is asked for its position, it just delegates to the injected positionable. 

But, maybe we don't need to make `IInventory` have a position at all. We could make a third interface `IStoreableLocation extends IStorable, IPositionable` which is what is taken in by the constructor above. In that case, `Stockpile` would have to implement `IStoreableLocation` instead, while `IInventory` still can have no position.

I don't know, maybe this is all just making it unnecessarily complicated. It just seemed a bit smelly to me that we had to pass around a position next to the interfaces all the time.

2021-10-23 17:51 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
Yeah, right now it's any item, should probably swap it to so you have to give an item type to remove, just like the TakeItemAction.

2021-10-23 17:53 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
Yeah, if you've got the time then that'd be better.

Would also eliminate the need for the `getNextItem` method, right?

2021-10-23 18:54 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
Depends if we want to loop through the inventory to get the next item to remove when emptying inventory for builders.

2021-10-23 18:57 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
What's wrong with looping? Am I sensing premature optimization 👀

2021-10-23 19:07 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
`performer.takeFirstItem()` vs 
`for (ItemType itemType : ItemType.values()) {
            if (performer.hasItem(itemType)) {
                return itemType;
            }
}`

I guess it's not that bad now that I've written that out, but I feel like wouldn't be unreasonable to have a `takeFirstItem` on an `Inventory`, or am I wrong?

2021-10-23 19:53 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +    private static final float MINIMUM_GIVE_DISTANCE = 2f;
The number of tiles, or do we have a measurement for what 1 tile is?

2021-10-24 03:09 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
Isn't that for-loop exactly what `tryTake(ItemType)` does?

2021-10-24 03:17 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
So since you're changing the action to only give items of a specific type, then it should be 
`performer.tryTake(itemType)` vs `performer.takeFirstItem()`.

Which means that `takeFirstItem` is redundant, because there's never a use case where a client doesn't care what item type it's taking.

2021-10-24 07:41 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
When the `BuilderRole` is emptying the inventory then it doesn't care what item's they are removing as they are removing all items, so inside of `BuilderRole` I'm just doing `takeFirstItem` and giving that `ItemType` to the `GiveItemAciton`, but if we want to loop inside `BuilderRole` then I can change it to that.

2021-10-24 07:50 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
At the beginning of this conversation we discussed how `GiveItemAction` should only give *specific types* of items:

>Yeah, right now it's any item, should probably swap it to so you have to give an item type to remove, just like the TakeItemAction.

So what you're saying here:

>When the `BuilderRole` is emptying the inventory then it doesn't care what item's they are removing as they are removing all items

no longer applies, right? That's how it worked before. But now we want `GiveItemAction` to only give items of a specific type. So the `BuilderRole` *does* care, or have I misunderstood?

I'm talking about the `GiveItemAction`, are you talking about another action `GiveAnyItemAction`?

2021-10-24 08:27 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
Right now `GiveAnyItemAction` and `BuilderRole` is using the `GiveItemAction` and the item given to `GivenItemAction` is decided with the `takeFirstItem`.

Want me to add the `GiveAnyItemAction` and use that instead?

2021-10-24 08:36 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
So you're saying there is a `GiveAnyItemAction` that delegates to `GiveItemAction`? But then you're asking if you should add `GiveAnyItemAction`, so it's not a thing? I'm completely lost.

Let's start over.

>question
It's a bit confusing that the action is GiveItem but in the constructor you never specify which item to give. So is it more like GiveAnyItem? Or how does it pick which item to give?

>Yeah, right now it's any item, should probably swap it to so you have to give an item type to remove, just like the TakeItemAction.

Are we or are we not making `GiveItemAction` take in an itemtype in its constructor? And if we are, then what is the need for `takeFirstItem`, since it's only used inside the `GiveItemAction` to get around the fact that it doesn't know which item to ask for.

2021-10-24 09:01 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
Actually, this isn't really important enough to spend too much time discussing. Keep it as-is if you want, we should focus on merging this PR instead.

2021-10-24 09:09 UTC, Matte02 commented on src/main/java/com/thebois/models/beings/actions/GiveItemAction.java
> +        final IStorable storable, final Position storablePosition) {
`GiveItemAction` is now changed to take in `ItemType` in the constructor.

Then in `BuilderRole` in order to decide what `Item` to remove, it would be nice to have `getFirstTypeOfItem`(just realized I can't use `takeFirstItem` cause that removes same type of item twice without being added twice.) or something since when emptying the inventory the `BuilderRole` doesn't care what `Item` to remove just that all `Item`s should be removed.

If I'm not making myself understood, we could start a zoom meeting and discuss it there, if you have time.

2021-10-24 12:21 UTC, martinjonsson01 approved these changes
Looking good!

Sat and actually played the game for a good 10 minutes and it's actually quite entertaining now!

Didn't find any bugs other than the ones Jacob already mentioned.

2021-10-24 12:21 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/inventory/ITakeable.java
> +     * Gets the ItemType of the first item.
style

of *any* item

2021-10-24 14:54 UTC, martinjonsson01 commented on src/main/java/com/thebois/models/world/World.java
> +    private boolean isSameType(final StructureType type, final IStructure structure) {
This name doesn't reflect the fact that it also checks for `|| isStorable(structure, type)`

2021-10-24 15:18 UTC, jonathan-lindqvist approved these changes
LGTM!
![image](https://user-images.githubusercontent.com/47867973/138600538-7fc20fa3-6236-4f53-ab63-06c83cd01d7a.png)

2021-10-24 16:07 UTC, merged