Add new project automation workflow
martinjonsson01/OOPP-WITH-THE-BOIS pull request #21
Opened 2021-09-15 15:43 UTC by martinjonsson01

This workflow should make issues (user stories) automatically
move to the "In progress" column on sprint board 1 when they are
assigned to someone.

2021-09-15 15:49 UTC, martinjonsson01 commented
Kom på nu att jag inte riktigt tänkte igenom denna, vi kanske vill ha det så att man kan assigna flera user stories till en person och sen kan man välja vilken som man arbetar på genom att manuellt flytta till "In progress"?

2021-09-15 16:30 UTC, JacobBredin approved these changes

2021-09-15 17:30 UTC, jonathan-lindqvist requested changes
Great idea, fun to play around with automation and learn what can be done.

Though I think we should add all our projects so that we don't have to go back and update this file for every project.

2021-09-15 17:30 UTC, jonathan-lindqvist commented on .github/workflows/automate-in-progress.yml
> +          project: Sprint 1
If I understand this correctly we will have to add this for each and every sprint/milestone? Might as well add all our sprints/milestones at the same time.

2021-09-15 17:36 UTC, martinjonsson01 commented on .github/workflows/automate-in-progress.yml
> +          project: Sprint 1
Yeah that's right, I was thinking we update it every time we move on to the next sprint. We might forget to sometime, though. 

I think the problem with adding all sprints at once is that once we've moved on to sprint 2, we no longer want it to add issues that have been assigned to sprint 1, right? I think it'll still do that if we don't remove it.

2021-09-16 07:17 UTC, jonathan-lindqvist commented on .github/workflows/automate-in-progress.yml
> +          project: Sprint 1
We have a "unique" setup with a new board for every sprint, but in general something that was not completed in the previous sprint should (probably) be part of the next sprint (and probably with higher proority).  So the question is do we want each sprint to be a milestone or not?

2021-09-16 07:22 UTC, martinjonsson01 commented on .github/workflows/automate-in-progress.yml
> +          project: Sprint 1
We could use a single board for all our sprints, then the "To Do" column could be the stories we plan to finish during the current sprint. That would also mean we wouldn't have to update the issue automation tasks.

The downside with that being we won't have a record of which stories were completed in which sprint. But maybe that could be remedied by the use of milestones? If a user story is finished during the "Proof of Concept" sprint, then you could go back and look at the closed issue and see that it was assigned to that milestone. This would eliminate the need for multiple sprint boards.

And yeah, in this case that would mean milestone=sprint. Would that cause any problems?

2021-09-16 07:33 UTC, jonathan-lindqvist commented on .github/workflows/automate-in-progress.yml
> +          project: Sprint 1
Don't see any problem with it atm, only that someitmes we will probably not complete a whole milestone in one sprint, but I would say that is normal. Aslong as we can see what is being worked on and what needs to be worked on 😄

2021-09-16 07:34 UTC, jonathan-lindqvist approved these changes
Resolve the discussion if you agree, then you can merge 👍

2021-09-16 07:39 UTC, martinjonsson01 commented
Alright, changed the board to just "Sprint" and will rename our current board from "Sprint 1" to "Sprint".

2021-09-16 07:41 UTC, merged